// import {
//   BodyGet,
//   BuyerSelect,
//   CardHeaderPeriod,
//   CardNote,
//   CardNotePeriod,
//   CardReport,
//   CardReportPeriod,
//   CardTreePeriod,
//   CardTreePeriodNusira,
//   CardTreePeriodVar,
//   Checkbox,
//   CheckboxFormDivisi,
//   CompanySelect,
//   ContentHeader,
//   DateControl,
//   ExcelButton,
//   FavoriteAdd,
//   FavStatusGet,
//   HeaderGet,
//   LoadingSpinner,
//   MachineSelect,
//   ParsedDateGet,
//   PartSelect,
//   PeriodSelect,
//   PlantSelect,
//   PlasticSelect,
//   ProcessButton,
//   SupplierSelect,
//   TreeColumns,
//   WarehouseSelect,
//   WidgetReport,
//   WidgetTemplate,
// } from './Components'
import {
  Alerts,
  Badges,
  BrandButtons,
  Breadcrumbs,
  ButtonDropdowns,
  ButtonGroups,
  Buttons,
  Cards,
  Carousels,
  Charts,
  Collapses,
  Colors,
  CoreUIIcons,
  Dropdowns,
  Flags,
  FontAwesome,
  Forms,
  Jumbotrons,
  ListGroups,
  Modals,
  Navbars,
  Navs,
  Paginations,
  Popovers,
  ProgressBar,
  SimpleLineIcons,
  Switches,
  Tables,
  Tabs,
  Tooltips,
  Typography,
  Users,
  Widgets,
} from './CoreUI';
import {
  Dashboard
} from './Dashboard';
import {
  Login,
  Page404,
  Page500,
  Register,
  Maintenance,
  Declaration
} from './Pages';

export {
  // BodyGet,
  // BuyerSelect,
  // CardHeaderPeriod,
  // CardNote,
  // CardNotePeriod,
  // CardReport,
  // CardReportPeriod,
  // CardTreePeriod,
  // CardTreePeriodNusira,
  // CardTreePeriodVar,
  // Checkbox,
  // CheckboxFormDivisi,
  // CompanySelect,
  // ContentHeader,
  // DateControl,
  // ExcelButton,
  // FavoriteAdd,
  // FavStatusGet,
  // HeaderGet,
  // LoadingSpinner,
  // MachineSelect,
  // ParsedDateGet,
  // PartSelect,
  // PeriodSelect,
  // PlantSelect,
  // PlasticSelect,
  // ProcessButton,
  // SupplierSelect,
  // TreeColumns,
  // WarehouseSelect,
  // WidgetReport,
  // WidgetTemplate,

  Alerts,
  Badges,
  BrandButtons,
  Breadcrumbs,
  ButtonDropdowns,
  ButtonGroups,
  Buttons,
  Cards,
  Carousels,
  Charts,
  Collapses,
  Colors,
  CoreUIIcons,
  Dropdowns,
  Flags,
  FontAwesome,
  Forms,
  Jumbotrons,
  ListGroups,
  Modals,
  Navbars,
  Navs,
  Paginations,
  Popovers,
  ProgressBar,
  SimpleLineIcons,
  Switches,
  Tables,
  Tabs,
  Tooltips,
  Typography,
  Users,
  Widgets,

  Dashboard,

  Login,
  Page404,
  Page500,
  Register,
  Maintenance,
  Declaration,
};
